### ADD item to Cart with cartId no presente
# @name addItemToCart
POST http://localhost:3333/cart
content-type: application/json

{
  "productId": "e5cf0f9c-3f3d-4d26-8b65-165cc1aa778a",
  "quantity": 2  
}

### ADD item to Cart with cartId presente
# @name addItemToCartExistent
POST http://localhost:3333/cart
content-type: application/json

{
  "cartId": "{{ addItemToCart.response.body.$.id }}",
  "productId": "e5cf0f9c-3f3d-4d26-8b65-165cc1aa778a"  
}


### Increment item to Cart
# @name incrementItemToCartItem
PATCH http://localhost:3333/cart/{{ addItemToCart.response.body.$.id }}/{{ addItemToCart.response.body.items[0].id }}
content-type: application/json

{
  "action": "increment"
}

### Decrement item to Cart
# @name decrementItemToCartItem
PATCH http://localhost:3333/cart/{{ addItemToCart.response.body.$.id }}/{{ addItemToCart.response.body.items[0].id }}
content-type: application/json

{
  "action": "decrement"
}