### CREATE Product
# @name createProduct
POST http://localhost:3333/products
content-type: application/json

{
  "name": "Malbec 02 Masculino 100ml",
  "description": "Experimente a refrescância única de Kaiak Desodorante Colônia Masculino. Sinta-se revigorado e confiante!"
}

### List Products
# @name findProduct
GET http://localhost:3333/products
  ?query=
  &skip=0
  &take=4
content-type: application/json
