const products = [
  { name: 'Ekos Ryo Chuva 75 ml', description: "No Desodorante Colônia Ekos Ryo Chuva capturamos a bioessência de uma chuva amazônica, que carrega a mistura de cheiros exuberantes da floresta molhada – para uma fragrância viva e intensa." },
  { name: 'Polpa Hidratante para as Mãos Ekos Castanha', description: 'A Polpa Natura Ekos Castanha para mãos é um poderoso creme antirressecamento, elaborado com óleo bruto de castanha. Essa fórmula nutre profundamente a pele e as unhas, melhorando visivelmente sua textura e resistência. A Polpa Hidratante Natura é ideal para proporcionar hidratação intensa e duradoura, deixando mãos macias, suaves e com uma aparência saudável.' },
  { name: "Malbec 02 Masculino 100ml", description: "Experimente a refrescância única de Kaiak Desodorante Colônia Masculino. Sinta-se revigorado e confiante!" },
  { name: "Ekos Castanha Polpa Hidratante para Mãos", description: "Hidratante para mãos com óleo de castanha, que nutre e protege a pele." },
  { name: "Chronos Acqua Biohidratante Renovador", description: "Hidratante facial que promove a renovação da pele e hidratação profunda." },
  { name: "Mamãe e Bebê Colônia", description: "Colônia suave e delicada, ideal para bebês e mães, com fragrância leve." },
  { name: "Tododia Creme Nutritivo para o Corpo", description: "Creme corporal nutritivo com fragrância suave, ideal para uso diário." },
  { name: "Kaiak Pulso Desodorante Colônia", description: "Desodorante colônia com fragrância refrescante e energizante." },
  { name: "Ekos Maracujá Óleo Trifásico", description: "Óleo corporal trifásico com fragrância de maracujá, que hidrata e perfuma a pele." },
  { name: "Una Base Líquida Radiance", description: "Base líquida com acabamento radiante e cobertura média, ideal para todos os tipos de pele." },
  { name: "Ekos Andiroba Sabonete Líquido", description: "Sabonete líquido com óleo de andiroba, que limpa e hidrata a pele." },
  { name: "Chronos Creme Antissinais", description: "Creme antissinais que reduz rugas e linhas de expressão, promovendo uma pele mais firme e hidratada." },
  { name: "Tododia Sabonete em Barra", description: "Sabonete em barra com fragrância suave, que limpa e hidrata a pele." },
  { name: "Kaiak Aventura Desodorante Colônia", description: "Desodorante colônia com fragrância fresca e aventureira." },
  { name: "Ekos Pitanga Polpa Hidratante para o Corpo", description: "Hidratante corporal com fragrância de pitanga, que nutre e perfuma a pele." },
  { name: "Una Batom Matte", description: "Batom com acabamento matte e alta pigmentação, disponível em diversas cores." },
  { name: "Mamãe e Bebê Shampoo", description: "Shampoo suave e delicado, ideal para o uso diário em bebês." },
  { name: "Chronos Sérum Preenchedor", description: "Sérum facial que preenche rugas e linhas de expressão, promovendo uma pele mais jovem." },
  { name: "Tododia Hidratante Corporal", description: "Hidratante corporal com fragrância suave, ideal para uso diário." },
  { name: "Kaiak Urbe Desodorante Colônia", description: "Desodorante colônia com fragrância urbana e moderna." },
  { name: "Ekos Açaí Polpa Hidratante para o Corpo", description: "Hidratante corporal com fragrância de açaí, que nutre e perfuma a pele." },
  { name: "Una Máscara para Cílios", description: "Máscara para cílios que proporciona volume e definição, disponível em diversas cores." },
  { name: "Mamãe e Bebê Loção Hidratante", description: "Loção hidratante suave e delicada, ideal para o uso diário em bebês." },
  { name: "Chronos Gel Creme Antissinais", description: "Gel creme antissinais que reduz rugas e linhas de expressão, promovendo uma pele mais firme e hidratada." },
  { name: "Tododia Sabonete Líquido", description: "Sabonete líquido com fragrância suave, que limpa e hidrata a pele." },
  { name: "Kaiak Oceano Desodorante Colônia", description: "Desodorante colônia com fragrância refrescante e marítima." },
  { name: "Ekos Buriti Óleo Trifásico", description: "Óleo corporal trifásico com fragrância de buriti, que hidrata e perfuma a pele." },
  { name: "Una Pó Compacto", description: "Pó compacto com acabamento matte e cobertura média, ideal para todos os tipos de pele." },
  { name: "Mamãe e Bebê Sabonete Líquido", description: "Sabonete líquido suave e delicado, ideal para o uso diário em bebês." },
  { name: "Chronos Creme Noturno", description: "Creme noturno que hidrata e revitaliza a pele durante a noite." },
  { name: "Tododia Creme para Mãos", description: "Creme para mãos com fragrância suave, que hidrata e protege a pele." },
  { name: "Kaiak Extremo Desodorante Colônia", description: "Desodorante colônia com fragrância intensa e marcante." },
  { name: "Ekos Maracujá Sabonete em Barra", description: "Sabonete em barra com fragrância de maracujá, que limpa e hidrata a pele." },
  { name: "Una Delineador Líquido", description: "Delineador líquido com alta pigmentação e longa duração, disponível em diversas cores." },
  { name: "Mamãe e Bebê Óleo Vegetal", description: "Óleo vegetal suave e delicado, ideal para o uso diário em bebês." },
  { name: "Chronos Sérum Clareador", description: "Sérum facial que clareia manchas e uniformiza o tom da pele." },
  { name: "Tododia Desodorante Roll-On", description: "Desodorante roll-on com fragrância suave, que protege e perfuma a pele." },
  { name: "Kaiak Aventura Sabonete em Barra", description: "Sabonete em barra com fragrância fresca e aventureira." },
  { name: "Ekos Andiroba Óleo Trifásico", description: "Óleo corporal trifásico com fragrância de andiroba, que hidrata e perfuma a pele." },
  { name: "Una Base Compacta", description: "Base compacta com acabamento matte e cobertura média, ideal para todos os tipos de pele." },
  { name: "Mamãe e Bebê Creme para Assaduras", description: "Creme para assaduras suave e delicado, ideal para o uso diário em bebês." },
  { name: "Chronos Creme Diurno", description: "Creme diurno que hidrata e protege a pele durante o dia." },
  { name: "Tododia Sabonete Líquido Esfoliante", description: "Sabonete líquido esfoliante com fragrância suave, que limpa e renova a pele." },
  { name: "Kaiak Pulso Sabonete em Barra", description: "Sabonete em barra com fragrância refrescante e energizante." },
  { name: "Ekos Pitanga Óleo Trifásico", description: "Óleo corporal trifásico com fragrância de pitanga, que hidrata e perfuma a pele." },
  { name: "Una Blush Compacto", description: "Blush compacto com acabamento matte e alta pigmentação, disponível em diversas cores." },
  { name: "Mamãe e Bebê Água de Colônia", description: "Água de colônia suave e delicada, ideal para o uso diário em bebês." },
  { name: "Chronos Máscara Facial", description: "Máscara facial que hidrata e revitaliza a pele, promovendo uma aparência mais jovem." }
]

export { products }
